name: MinezinServer
version: '1.2'
main: com.engenhoso.serverplugin.MinezinServer
api-version: '1.21'
authors: [Engenhoso]
description: Plug-in oficial do MinezinServer

commands:
  renomearfada:
    description: Renomeia a fada do jogador
    usage: /renomearfada <novo_nome>
  invocarfada:
    description: invoca sua fada manualmente
    usage: /invocarfada
  sumirfada:
    description: Faz sua fada sumir temporariamente
    usage: /sumirfada
