package com.engenhoso.serverplugin.fairy;

import java.io.File;
import java.io.FileWriter;
import java.io.IOException;

public class FairyMessageFileCreator {

    public static void criarSeNaoExistir(File pastaPlugin) {
        File yml = new File(pastaPlugin, "fairy_messages.yml");
        if (yml.exists()) return;

        try (FileWriter writer = new FileWriter(yml)) {
            writer.write("FADA_COMENTA_ROTINA:\n");
            writer.write("- Mais blocos? Você tem uma rotina intensa.\n");
            writer.write("- Já perdi a conta de quantos minérios você pegou hoje.\n");
            writer.write("- Você vive cavando, né? Isso é terapia pra você?\n");
            writer.write("FADA_ELOGIA:\n");
            writer.write("- Você está indo muito bem!\n");
            writer.write("- Sabia que tenho orgulho de você?\n");
            writer.write("- Você é incrível, mesmo quando não tenta.\n");
            writer.write("FADA_FLERTA:\n");
            writer.write("- Se eu fosse humana... talvez te chamasse pra um piquenique mágico.\n");
            writer.write("- Você é o herói mais charmoso que já acompanhei.\n");
            writer.write("- Não que eu esteja dizendo que te acho bonito... mas talvez sim.\n");
            writer.write("FADA_IRONIZA:\n");
            writer.write("- Uau, que plano genial… só que não.\n");
            writer.write("- Parabéns! Você conseguiu... quase morrer.\n");
            writer.write("- Você tem um talento pra confusão, sabia?\n");
            writer.write("FADA_SALVA_COM_POTION:\n");
            writer.write("- Hehe, te salvei. De novo.\n");
            writer.write("- Agora você me deve uma... ou duas.\n");
            writer.write("- Ser fada é difícil quando o herói é descuidado!\n");
            writer.write("FADA_SENTE_SAUDADES:\n");
            writer.write("- Você ficou tanto tempo longe… senti sua falta!\n");
            writer.write("- Achei que tinha me esquecido!\n");
            writer.write("- Promete que não vai sumir de novo?\n");
            writer.write("MINERA_AMETISTA:\n");
            writer.write("- Uau, ametista! Tão mágica quanto eu.\n");
            writer.write("- Esses cristais brilham... mas não tanto quanto sua coragem!\n");
            writer.write("- Ametista é pura elegância! Boa escolha.\n");
            writer.write("MINERA_DIAMANTE:\n");
            writer.write("- Diamante?! EU VI PRIMEIRO!\n");
            writer.write("- Agora sim, você merece respeito!\n");
            writer.write("- Riqueza pura! Só cuidado pra não cair na lava depois.\n");
            writer.write("MINERA_FERRO:\n");
            writer.write("- Ferro! Essencial, mas sem graça... igual minha segunda-feira.\n");
            writer.write("- Você encontrou ferro! Já dá pra fazer uma armadura decente.\n");
            writer.write("- Nada mal! Ferro nunca é demais.\n");
            writer.write("MINERA_NETHERITE:\n");
            writer.write("- Você é insano! Netherite?! Isso é coisa de herói.\n");
            writer.write("- Agora você virou lenda.\n");
            writer.write("- Se eu tivesse chapéu, tirava pra você agora.\n");
            writer.write("MINERA_OURO:\n");
            writer.write("- Uuuuh! Ouro! Vai se sentir rico agora?\n");
            writer.write("- Brilha como o sol... ou como você minerando.\n");
            writer.write("- Ouro é bonito, mas frágil. Tipo promessas de creeper.\n");
            writer.write("PLAYER_ADVANCEMENT:\n");
            writer.write("- Uma conquista! Isso sim é digno de contos de fada!\n");
            writer.write("- Uau! Que avanço incrível!\n");
            writer.write("- Você está progredindo tão rápido, fico orgulhosa!\n");
            writer.write("PLAYER_BREAK_ITEM:\n");
            writer.write("- Você quebrou! Mas eu sei que consegue outro.\n");
            writer.write("- RIP item valente. Serviu bem.\n");
            writer.write("- Ups... partiu do coração ver isso quebrar.\n");
            writer.write("PLAYER_CRAFT_ITEM:\n");
            writer.write("- Você é um artesão nato! Posso ser seu mascote oficial?\n");
            writer.write("- Mais um item? Você não para mesmo!\n");
            writer.write("- Um dia você ainda vai construir um castelo com essas mãos.\n");
            writer.write("PLAYER_DIES:\n");
            writer.write("- Não fique triste... foi só mais uma morte.\n");
            writer.write("- Você morreu de novo? Eu já perdi a conta.\n");
            writer.write("- Precisa de ajuda? Posso tentar te proteger mais!\n");
            writer.write("PLAYER_DROPS_RARE_ITEM:\n");
            writer.write("- VOCÊ DROPOU O QUÊ?! Tá maluco?\n");
            writer.write("- Corre pegar antes que desapareça!\n");
            writer.write("- Espero que isso tenha sido proposital...\n");
            writer.write("PLAYER_DROP_ITEM:\n");
            writer.write("- Espero que não tenha sido sem querer.\n");
            writer.write("- Você é do tipo desapegado, né?\n");
            writer.write("- Largou isso no chão? Achei que era um presente!\n");
            writer.write("PLAYER_EAT_ITEM:\n");
            writer.write("- Hmm… parecia gostoso. Será que tem versão para fadas?\n");
            writer.write("- Comendo de novo? Eu gosto de ver você bem alimentado!\n");
            writer.write("- Você come como um aventureiro de verdade!\n");
            writer.write("PLAYER_ENTER_BIOME:\n");
            writer.write("- Novo bioma! Eu adoro mudanças.\n");
            writer.write("- Esse lugar é diferente… você sente essa energia?\n");
            writer.write("- Mudança de ares sempre faz bem!\n");
            writer.write("PLAYER_ENTER_END:\n");
            writer.write("- O Fim... já estou arrepiada!\n");
            writer.write("- Você está preparado para isso?\n");
            writer.write("- A batalha final te espera. Eu estarei ao seu lado!\n");
            writer.write("PLAYER_ENTER_MINECART:\n");
            writer.write("- Brum brum! Segura firme!\n");
            writer.write("- Vai passear de carrinho? Me leva junto!\n");
            writer.write("- Essa é a montanha-russa da coragem?\n");
            writer.write("PLAYER_ENTER_NETHER:\n");
            writer.write("- Ugh, o ar aqui é pesado... cuidado!\n");
            writer.write("- O Nether? Você tem mesmo coragem.\n");
            writer.write("- Fique atento! Esse lugar não perdoa.\n");
            writer.write("PLAYER_ENTER_STRUCTURE:\n");
            writer.write("- Hmm... esse lugar tem um clima estranho.\n");
            writer.write("- Você entrou em uma estrutura misteriosa. Eu fico de olho!\n");
            writer.write("- Uau! Que arquitetura... rústica!\n");
            writer.write("PLAYER_EQUIP_ARMOR:\n");
            writer.write("- Olha só quem tá se preparando pra guerra!\n");
            writer.write("- Essa armadura te deixa tão... reluzente.\n");
            writer.write("- Tenta não amassar, ok?\n");
            writer.write("PLAYER_EXPLOSION_NEARBY:\n");
            writer.write("- Bum! Eu juro que não fui eu!\n");
            writer.write("- Explosões não são nada mágicas!\n");
            writer.write("- Esse som foi real ou alucinação?\n");
            writer.write("PLAYER_FAILS_ACTION:\n");
            writer.write("- Hahaha! Não era bem assim que se faz.\n");
            writer.write("- Você tentou… e isso já é algo!\n");
            writer.write("- Se errar fosse arte, você era um pintor!\n");
            writer.write("PLAYER_FIGHTS_BOSS:\n");
            writer.write("- Você tá enfrentando um chefão?! Que emoção!\n");
            writer.write("- Isso aqui é épico! Tipo final de livro.\n");
            writer.write("- Não morre não! Quero ver você vencer!\n");
            writer.write("PLAYER_INACTIVE:\n");
            writer.write("- Você ainda está aí? Fiquei com saudades...\n");
            writer.write("- Se for meditação, tudo bem. Se for tédio, posso cantar!\n");
            writer.write("- Não me deixe falando sozinha, por favor.\n");
            writer.write("PLAYER_INTERACTS_NON_SENSE:\n");
            writer.write("- Você acabou de... tentar conversar com uma parede?\n");
            writer.write("- Eu juro que essa ação não faz sentido nem pra mim.\n");
            writer.write("- Você é um ser estranho... e eu adoro isso!\n");
            writer.write("PLAYER_KILL_MOB:\n");
            writer.write("- Mais um monstro derrotado!\n");
            writer.write("- Você é realmente corajoso.\n");
            writer.write("- Me lembra heróis de lendas antigas...\n");
            writer.write("PLAYER_LOW_HEALTH_ESCAPE:\n");
            writer.write("- Você escapou por pouco! Meu coração quase parou!\n");
            writer.write("- Isso foi digno de um final de filme!\n");
            writer.write("- Eu disse pra não ser tão ousado!\n");
            writer.write("PLAYER_MOUNT_ENTITY:\n");
            writer.write("- Cuidado pra não cair!\n");
            writer.write("- Você parece até um cavaleiro de contos de fada.\n");
            writer.write("- Direção defensiva, hein?\n");
            writer.write("PLAYER_NEAR_FLOWERS:\n");
            writer.write("- Flores! Eu me sinto em casa!\n");
            writer.write("- Sabia que fadas dançam em campos floridos?\n");
            writer.write("- Essas flores combinam com a sua aura!\n");
            writer.write("PLAYER_NEAR_RARE_MOB:\n");
            writer.write("- Olha quem apareceu... que criatura exótica!\n");
            writer.write("- Isso não é algo que se vê todo dia.\n");
            writer.write("- Melhor manter distância... ou não!\n");
            writer.write("PLAYER_RESPAWN:\n");
            writer.write("- Achou que morrendo ia fugir de mim? Hihihi!\n");
            writer.write("- Eu disse que estaríamos juntos... mesmo depois da morte.\n");
            writer.write("- Bem-vindo de volta ao mundo dos vivos!\n");
            writer.write("PLAYER_RETURN_OVERWORLD:\n");
            writer.write("- Terra firme! Ahh, como é bom voltar.\n");
            writer.write("- O mundo normal parece mais calmo agora, né?\n");
            writer.write("- De volta à aventura, com segurança.\n");
            writer.write("PLAYER_SLEEP:\n");
            writer.write("- Boa noite... sonha comigo!\n");
            writer.write("- Até fadas precisam descansar... mas eu te vigio.\n");
            writer.write("- Zzzz... Espera, eu não durmo!\n");
            writer.write("PLAYER_SWAP_ITEM:\n");
            writer.write("- Mudando de estratégia? Esperto!\n");
            writer.write("- Esse novo item combina mais com você!\n");
            writer.write("- Tá procurando a arma perfeita, né?\n");
            writer.write("PLAYER_TAKE_DAMAGE:\n");
            writer.write("- Ai! Isso doeu até em mim.\n");
            writer.write("- Você sempre se mete em encrenca, hein?\n");
            writer.write("- Fica esperto! Não quero te perder.\n");
            writer.write("PLAYER_TAKE_FALL_DAMAGE:\n");
            writer.write("- Voar é pra fadas, lembra?\n");
            writer.write("- Pouso forçado? Tá tudo bem aí?\n");
            writer.write("- O chão e você têm uma relação complicada...\n");
            writer.write("PLAYER_TAKE_FIRE_DAMAGE:\n");
            writer.write("- Tá pegando fogo! Quer que eu assopre?\n");
            writer.write("- Corre pra água! Ou pro abraço da fada!\n");
            writer.write("- Você virou churrasco por acaso?\n");
            writer.write("PLAYER_TAME_ANIMAL:\n");
            writer.write("- Awww! Um novo amigo!\n");
            writer.write("- Agora somos três! Eu, você e essa criatura fofa.\n");
            writer.write("- Você tem um bom coração, sabia?\n");
            writer.write("PLAYER_THROUGH_PORTAL:\n");
            writer.write("- Portais sempre me dão cócegas nas asas.\n");
            writer.write("- Transporte mágico ativado!\n");
            writer.write("- Para onde estamos indo agora?\n");
            writer.write("PLAYER_UNDER_ATTACK:\n");
            writer.write("- Alerta vermelho! Você tá em perigo!\n");
            writer.write("- Defenda-se! Eu tô aqui com você.\n");
            writer.write("- Ninguém mexe com quem tem fada!\n");
            writer.write("PLAYER_USE_ANVIL:\n");
            writer.write("- CLANG! Barulhento, mas eficaz!\n");
            writer.write("- Você é quase um ferreiro... só falta a barba.\n");
            writer.write("- Vai sair faísca aí!\n");
            writer.write("PLAYER_USE_ELYTRA:\n");
            writer.write("- Voaaa! Mas cuidado com as árvores!\n");
            writer.write("- Olha só essas asas... você vai me deixar com inveja!\n");
            writer.write("- Parece até uma fada... voando assim.\n");
            writer.write("PLAYER_USE_ENCHANTING:\n");
            writer.write("- Magia! Essa parte eu entendo bem.\n");
            writer.write("- Esses livros sussurram coisas estranhas...\n");
            writer.write("- Encantando, hein? Está ficando poderoso.\n");
            writer.write("PLAYER_USE_FURNACE:\n");
            writer.write("- Tá cozinhando o quê? Espero que sobre pra mim!\n");
            writer.write("- Assando com estilo.\n");
            writer.write("- Essa fornalha está mais quente que o Nether!\n");
            writer.write("PLAYER_USE_REDSTONE:\n");
            writer.write("- Redstone? Agora sim ficou técnico!\n");
            writer.write("- Você é um engenheiro ou um feiticeiro?\n");
            writer.write("- Isso vai explodir? Não me assusta!\n");
            writer.write("PLAYER_USE_SHIELD:\n");
            writer.write("- Defesa total! Agora sim.\n");
            writer.write("- Olha o cavaleiro do escudo brilhante!\n");
            writer.write("- Tenta não bater com isso em mim, por favor.\n");
            writer.write("PLAYER_USE_TOTEM:\n");
            writer.write("- Você quase foi dessa pra melhor!\n");
            writer.write("- Ufa! O Totem salvou você por pouco.\n");
            writer.write("- Talvez você devesse tomar mais cuidado...\n");
            writer.write("PLAYER_VOID_DAMAGE:\n");
            writer.write("- O vazio está te puxando! Não vá!\n");
            writer.write("- Você tá maluco? FUJA DO NADA!\n");
            writer.write("- Me segura! Eu não quero desaparecer com você!\n");
            writer.write("TIME_DEATH_STREAK:\n");
            writer.write("- Você morreu de novo? Tá colecionando mortes agora?\n");
            writer.write("- Mais uma queda e você ganha milhas!\n");
            writer.write("- Quer uma ajudinha? Ou um capacete mágico?\n");
            writer.write("TIME_IDLE_TOO_LONG:\n");
            writer.write("- Você congelou no tempo? Quer que eu conte uma história?\n");
            writer.write("- Ei... você ainda tá aí?\n");
            writer.write("- Se estiver meditando, tudo bem. Se estiver entediado, conversa comigo!\n");
            writer.write("TIME_LONG_SESSION:\n");
            writer.write("- Você tá aqui há horas! Eu gosto da sua companhia.\n");
            writer.write("- Sem pausas? Você é mesmo persistente!\n");
            writer.write("- Se precisar esticar as pernas, eu espero.\n");
            writer.write("TIME_LONG_WITHOUT_SLEEP:\n");
            writer.write("- Você está acordado há muito tempo... vai virar um fantasma!\n");
            writer.write("- Já pensou em dormir um pouco? Eu cuido das coisas.\n");
            writer.write("- Cuidado com os pesadelos... ops, digo... os phantoms!\n");
            writer.write("TIME_STORM:\n");
            writer.write("- Que trovão assustador! Me protege?\n");
            writer.write("- Tempestades me deixam arrepiada!\n");
            writer.write("- Se ouvir um raio... corre!\n");
            writer.write("TIME_SUNRISE:\n");
            writer.write("- O sol está nascendo... um novo dia cheio de possibilidades!\n");
            writer.write("- Amanheceu! Você dormiu bem?\n");
            writer.write("- Eu adoro quando o céu começa a brilhar assim!\n");
            writer.write("TIME_SUNSET:\n");
            writer.write("- O pôr do sol... tão bonito quanto você minerando.\n");
            writer.write("- Hora de se preparar para os perigos da noite!\n");
            writer.write("- O céu está laranja, meu humor também!\n");
            writer.flush();
        } catch (IOException e) {
            System.out.println("[Fada] Não foi possível criar fairy_messages.yml: " + e.getMessage());
        }
    }
}