package com.engenhoso.serverplugin.modules.fairy.core;

public enum FairySituation {
    // AÇÕES DO JOGADOR
    PLAYER_CRAFT_ITEM,
    PLAYER_DROP_ITEM,
    PLAYER_EAT_ITEM,
    PLAYER_EQUIP_ARMOR,
    PLAYER_SWAP_ITEM,
    PLAYER_SLEEP,
    PLAYER_USE_ANVIL,
    PLAYER_USE_ENCHANTING,
    PLAYER_USE_FURNACE,
    PLAYER_TAME_ANIMAL,
    PLAYER_MOUNT_ENTITY,
    PLAYER_USE_ELYTRA,
    PLAYER_RESPAWN,
    PLAYER_DIES,
    PLAYER_ADVANCEMENT,
    PLAYER_USE_TOTEM,
    PLAYER_ENTER_MINECART,
    PLAYER_USE_SHIELD,
    PLAYER_BREAK_ITEM,

    // COMBATE E DANOS
    PLAYER_TAKE_DAMAGE,
    PLAYER_TAKE_FIRE_DAMAGE,
    PLAYER_TAKE_FALL_DAMAGE,
    PLAYER_EXPLOSION_NEARBY,
    PLAYER_KILL_MOB,
    PLAYER_UNDER_ATTACK,
    PLAYER_FIGHTS_BOSS,
    FADA_SALVA_COM_POTION,

    // INTERAÇÃO COM O MUNDO
    PLAYER_ENTER_STRUCTURE,
    PLAYER_ENTER_BIOME,
    PLAYER_NEAR_RARE_MOB,
    PLAYER_NEAR_FLOWERS,
    PLAYER_INACTIVE,
    PLAYER_USE_REDSTONE,

    // DIMENSÕES E VIAGEM
    PLAYER_ENTER_NETHER,
    PLAYER_ENTER_END,
    PLAYER_RETURN_OVERWORLD,
    PLAYER_THROUGH_PORTAL,
    PLAYER_VOID_DAMAGE,

    // TEMPO E CLIMA
    TIME_SUNRISE,
    TIME_SUNSET,
    TIME_STORM,
    TIME_LONG_WITHOUT_SLEEP,
    TIME_LONG_SESSION,
    TIME_IDLE_TOO_LONG,
    TIME_DEATH_STREAK,

    // COMPORTAMENTO E HUMOR
    PLAYER_FAILS_ACTION,
    PLAYER_LOW_HEALTH_ESCAPE,
    PLAYER_DROPS_RARE_ITEM,
    PLAYER_INTERACTS_NON_SENSE,

    // COMPORTAMENTO DA FADA
    FADA_SENTE_SAUDADES,
    FADA_ELOGIA,
    FADA_IRONIZA,
    FADA_COMENTA_ROTINA,
    FADA_FLERTA,

    // MINERIOS
    MINERA_FERRO,
    MINERA_OURO,
    MINERA_DIAMANTE,
    MINERA_NETHERITE,
    MINERA_AMETISTA,

    }